### PR TITLE
Flutter_resources

### PR DESCRIPTION
**Pull request by sAchin12320-web**
This file will contain all the important resources useful for our flutter learning.

### CODE REVIEW

**Comment by RitwikSingh28** [comment]
Great Initiative @sAchin12320-web ...

**Comment by sAchin12320-web** [comment]
Thanks.

**Comment by RitwikSingh28** [comment]
@SID048 @01Chhotu @03Simran @TRISHAHALDER 
Try and figure out how you could go about contributing to this PR, and add some links. 
It's a nice idea to learn by exploring things..... :sunglasses:

You have until 10 days to contribute to this PR, else I will close it without merging.

**Comment by RitwikSingh28** [comment]
If you plan on continuing work on this PR, let me know within the next **5 days**.

**Comment by sAchin12320-web** [comment]
Fine, I will be working on that

**Pull request closed without merging**
